services:
  postgres-db:
    image: postgres:15-alpine
    container_name: postgres_db
    environment:
      POSTGRES_DB: orymar_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  dao-service:
    build:
      context: .
      dockerfile: Dockerfile # шлях до універсального Dockerfile
      args:
        MODULE_NAME: dao
    container_name: dao_service
    ports:
      - "8081:8081"
    depends_on:
      - postgres-db
      - kafka
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/orymar_db
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:29092

  core-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MODULE_NAME: core-service
    container_name: core_service
    ports:
      - "8080:8080"
    depends_on:
      - dao-service
      - kafka
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/orymar_db
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:29092

# Сервіс common ВИДАЛЕНО

volumes:
  pgdata: